#!/bin/sh
# mvln

set -e

SCRIPTNAME='mvln'
VERSION='1.0.5'

mvln_main() {
	e_args=16
	e_missing_app=17

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt "$opt" ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && [ $# -lt 1 ] && cmd=help
	[ -z "$cmd" ] && cmd=process

	case "$cmd" in
		help|process|version) "mvln_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac
}

mvln_help() {
cat <<USAGE
$SCRIPTNAME $VERSION

USAGE: $scriptinv [<options>] <src1> [<src2>...] <dest>

Move source files and directories to destination and leave symlinks in their place.

OPTIONS:

	-h        Show this help screen.
	-v        Show version.

USAGE
}

mvln_process() {
	_require mv ln dirname realpath

	# Only the GNU version has the "--relative-to" option
	version=$(realpath --version)
	if [[ $version != *GNU* ]]; then
		_error "GNU version of realpath required"
		exit 1
	fi

	# get the last argument for the destination
	for dest; do true; done

	# dest is checked for a directory multiple times, just do it once here
	if [ -d "$dest" ]; then
		dest_is_dir=true
	else
		dest_is_dir=false
	fi

	# If more than two arguments are given, the last one must be a directory
	if [ $# -gt 2 ]; then
		if [ "$dest_is_dir" = false ]; then
			_error "target '${dest}' is not a directory"
			exit 1
		fi
	fi

	while [ $# -gt 1 ]
	do
		src="$1"

		# If the destination is a directory, we need to link to where the file will end up
		if [ "$dest_is_dir" = true ]; then
			src_dest="$dest/$( basename "$src" )"
		else
			src_dest="$dest"
		fi

		if [ -e "$src_dest" ]; then
			_error "target '${src_dest}' already exists"
			exit 1
		fi

		# use realpath to get a relative path to the destination
		target="$( realpath -s "$src_dest" --relative-to="$( dirname "$src" )" )"

		mv -n -v "$src" "$src_dest"
		ln -s "$target" "$(realpath -s "$src")"

		shift
	done
}

mvln_version() {
	echo "$SCRIPTNAME $VERSION"
}

_error() {
	echo "ERROR: $@" >&2
}

_invalid_cmd() {
	_error "Invalid command: $0"
	echo
	mvln_help
	exit $e_args
}

_invalid_opt() {
	exit $e_args
}

_require() {
	missing_bin=0

	for bin in "$@"
	do
		if ! which "$bin" > /dev/null 2>&1
		then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]
	then
		_error "One or more executables or apps are missing."
		exit "$e_missing_app"
	fi
}

mvln_main "$@"
