#!/bin/sh
# mvln

VERSION='1.0.3'

mvln_main() {
	e_args=16
	e_missing_app=17

	scriptinv="$( basename "$0" )"
	scriptpath="$( readlink -f "$0" )"
	scriptname="$( basename "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt "$opt" ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && [ $# -lt 1 ] && cmd=help
	[ -z "$cmd" ] && cmd=process

	case "$cmd" in
		help|process|version) "mvln_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac
}

mvln_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptinv [<options>] <src1> [<src2>...] <dest>

Move source files and directories to target and leave symlinks their place.

OPTIONS:

	-h        Show this help screen.
	-v        Show version.

USAGE
}

mvln_process() {
	_require realpath

	if [ $# -gt 2 ]; then
		for last_arg; do true; done

		if [ ! -d "$last_arg" ]; then
			_error "target '${last_arg}' is not a directory"
			exit 1
		fi
	fi

	while [ $# -gt 1 ]
	do
		# get the last argument for the destination
		for dest; do true; done

		src="$1"
		shift

		[ -d "$dest" ] && dest="$dest/$( basename "$src" )"

		mv -v "$src" "$dest"

		target="$( realpath "$dest" --relative-to="$( dirname "$src" )" )"

		ln -s "$target" "$(realpath -s $src)"
	done
}

mvln_version() {
	echo "$scriptname $VERSION"
}

_error() {
	echo "$@" >&2
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	echo
	mvln_help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	echo
	mvln_help
	exit $e_args
}

_require() {
	missing_bin=0

	for bin in "$@"
	do
		if ! which "$bin" > /dev/null 2>&1
		then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]
	then
		_fatal "$e_missing_app" "One or more executables or apps are missing."
	fi
}

mvln_main "$@"
